spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hello@123
    url: jdbc:mysql://47.110.67.96/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
