spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lzy@19911013
    url: jdbc:mysql://47.110.67.96:33306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
